### ISSUE TITLE
Exception on load downloaded xlsm

### ISSUE THREAD

**Issue by ufa3110** [EPPlusSoftware/EPPlus#1079]
### EPPlus usage

Noncommercial use

### Environment

Windows

### Epplus version

6.2.9

### Spreadsheet application

Excel

### Description

'o:relid' is a duplicate attribute name. Line 14, position 26.

 at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.AttributeDuplCheck()
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at OfficeOpenXml.XmlHelper.LoadXmlSafe(XmlDocument xmlDoc, String xml, Encoding encoding)
   at OfficeOpenXml.Drawing.Vml.ExcelVmlDrawingBaseCollection..ctor(ExcelWorksheet ws, Uri uri, String worksheetRelIdPath)
   at OfficeOpenXml.Drawing.Vml.ExcelVmlDrawingCollection..ctor(ExcelWorksheet ws, Uri uri)
   at OfficeOpenXml.ExcelWorksheet.CreateVmlCollection()
   at OfficeOpenXml.ExcelWorksheet.LoadComments()
   at OfficeOpenXml.ExcelWorksheet..ctor(XmlNamespaceManager ns, ExcelPackage excelPackage, String relID, Uri uriWorksheet, String sheetName, Int32 sheetID, Int32 positio
nID, Nullable`1 hide)
   at OfficeOpenXml.ExcelWorksheets..ctor(ExcelPackage pck, XmlNamespaceManager nsm, XmlNode topNode)
   at OfficeOpenXml.ExcelWorkbook.get_Worksheets()
   at OfficeOpenXml.ExcelWorkbook.GetDefinedNames()
   at OfficeOpenXml.ExcelPackage.get_Workbook()

[GSMControl v4.1 analog reset2 .xls](https://github.com/EPPlusSoftware/EPPlus/files/12748522/GSMControl.v4.1.analog.reset2.xls)

i didn't sure where it comes so just loaded my file
note that originaly its .xlsm file, just renamed for github upload compatibility

**Comment by ufa3110** [comment]
ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;
            FileInfo newFile = new FileInfo(filename);

            ExcelPackage pck = new ExcelPackage(newFile);
            var mainSheet = pck.Workbook.Worksheets.FirstOrDefault(s => s.Name == "АТТ")!;

**Comment by JanKallman** [comment]
The file is corrupt. 
It has a duplicate relid attributes in vmlDrawing1.vml, line 14...
`  <v:fill o:relid="rId1" o:relid="rId1" o:title="8X-4575" color2="infoBackground"`
