### ISSUE TITLE
Random ArgumentOutOfRangeException for CopyColumn

### ISSUE THREAD

**Issue by vivet** [EPPlusSoftware/EPPlus#1181]
Hi

I am getting the below exception randomly. It doesn't happen very often, maybe once or twice a month. I have seen it happen for several different excel files, so it's not related to any specific Excel file, why it's hard to provide an example.

```
ArgumentOutOfRangeException - Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at OfficeOpenXml.ExcelWorksheet.CopyColumn(ExcelColumn c, Int32 col, Int32 maxCol)
   at OfficeOpenXml.ExcelWorksheet.Column(Int32 col)
   at Svc.Xbrl.Input.Readers.ExcelXReader.<>c__DisplayClass10_0.<<ReadWorksheet>b__0>d.MoveNext() in /src/Svc.Xbrl/Input/Readers/ExcelXReader.cs:line 330
--- End of stack trace from previous location ---
   at Svc.Xbrl.Input.Readers.ExcelXReader.ReadWorksheet(ExcelWorksheet worksheet, CancellationToken cancellationToken) in /src/Svc.Xbrl/Input/Readers/ExcelXReader.cs:line 339
   at Svc.Xbrl.Input.Readers.ExcelXReader.Read(InputFile inputFile, InputSettings inputSettings, CancellationToken cancellationToken) in /src/Svc.Xbrl/Input/Readers/ExcelXReader.cs:line 137
   at Svc.Xbrl.Input.Services.InputReaderService.<>c__DisplayClass13_0.<<ReadInputFiles>b__0>d.MoveNext() in /src/Svc.Xbrl/Input/Services/InputReaderService.cs:line 222
--- End of stack trace from previous location ---
   at Svc.Xbrl.Input.Services.InputReaderService.ReadInputFiles(IEnumerable`1 inputFiles, InputSettings inputSettings, CancellationToken cancellationToken) in /src/Svc.Xbrl/Input/Services/InputReaderService.cs:line 279
   at Svc.Xbrl.Input.Services.InputReaderService.ReadFiles(IList`1 inputFiles, CancellationToken cancellationToken) in /src/Svc.Xbrl/Input/Services/InputReaderService.cs:line 66
   at Svc.Xbrl.Controllers.XbrlController.GenerateAsync(IEnumerable`1 files, Boolean saveFile, Boolean saveArtifacts, CancellationToken cancellationToken) in /src/Svc.Xbrl/Controllers/XbrlController.cs:line 130
```

**Comment by swmal** [comment]
Hi,

I can't see what's going wrong based on this stacktrace. Maybe you could add some additional logging to this? Would be great if you could log the value of `col` and number of sheets in the workbook where this happens.

**Comment by vivet** [comment]
I have added some logging, and will now wait for the exception to happen again
