### ISSUE TITLE
Null Exception when copying a sheet that has an image with a Hyperlink

### ISSUE THREAD

**Issue by Ionela13** [EPPlusSoftware/EPPlus#1203]
I am using your library to multiply a sheet which has an image with a Hyperlink, by using the `Add` method on the `Worksheets` collection.

This, however, generates the following Exception:
`Object reference not set to an instance of an object.`

and the following StackTrace:
`   at OfficeOpenXml.Utils.UriHelper.ResolvePartUri(Uri sourceUri, Uri targetUri)
   at OfficeOpenXml.Drawing.ExcelPicture..ctor(ExcelDrawings drawings, XmlNode node, ExcelGroupShape shape)
   at OfficeOpenXml.Drawing.ExcelDrawing.GetDrawingFromNode(ExcelDrawings drawings, XmlNode node, XmlElement drawNode, ExcelGroupShape parent)
   at OfficeOpenXml.Drawing.ExcelDrawings.AddDrawings()
   at OfficeOpenXml.Drawing.ExcelDrawings..ctor(ExcelPackage xlPackage, ExcelWorksheet sheet)
   at OfficeOpenXml.Core.Worksheet.WorksheetCopyHelper.CopyDrawing(ExcelPackage pck, XmlNamespaceManager nsm, ExcelWorksheet copy, ExcelWorksheet added)
   at OfficeOpenXml.Core.Worksheet.WorksheetCopyHelper.Copy(ExcelWorksheets worksheets, String name, ExcelWorksheet copy)
   at OfficeOpenXml.ExcelWorksheets.Add(String Name, ExcelWorksheet Copy)`

Could you please tell me how to solve this issue?

**Comment by JanKallman** [comment]
This is a bug. I will provide a fix shortly.

**Comment by JanKallman** [comment]
Fixed in 6.2.15 & 7.0.4
