### ISSUE TITLE
Memory streams are not disposed, version 7.0.6

### ISSUE THREAD

**Issue by kemsky** [EPPlusSoftware/EPPlus#1250]
This is the same problem as #1103.

Stack traces:

```
   at OfficeOpenXml.Utils.RecyclableMemory.GetStream()
   at OfficeOpenXml.Packaging.ZipPackagePart.GetStream(FileMode fileMode, FileAccess fileAccess)
   at OfficeOpenXml.ExcelWorkbook.get_StylesXml()
   at OfficeOpenXml.ExcelWorkbook.get_Styles()
   at OfficeOpenXml.ExcelRangeBase.get_Style()
   at Excel.Extensions.ExcelExtensions.WrapText(ExcelRange cell)
```

```
   at OfficeOpenXml.Utils.RecyclableMemory.GetStream()
   at OfficeOpenXml.Packaging.ZipPackagePart.GetStream(FileMode fileMode, FileAccess fileAccess)
   at OfficeOpenXml.OfficeProperties.GetXmlDocument(String startXml, Uri uri, String contentType, String relationship)
   at OfficeOpenXml.OfficeProperties.get_CustomPropertiesXml()
   at OfficeOpenXml.OfficeProperties..ctor(ExcelPackage package, XmlNamespaceManager ns)
   at OfficeOpenXml.ExcelWorkbook.get_Properties()
   at Excel.Extensions.ExcelExtensions.SetTitle
```

```
   at OfficeOpenXml.Utils.RecyclableMemory.GetStream()
   at OfficeOpenXml.Packaging.ZipPackagePart.GetStream(FileMode fileMode, FileAccess fileAccess)
   at OfficeOpenXml.ExcelWorkbook.CreateWorkbookXml(XmlNamespaceManager namespaceManager)
   at OfficeOpenXml.ExcelWorkbook.get_WorkbookXml()
   at OfficeOpenXml.ExcelWorkbook..ctor(ExcelPackage package, XmlNamespaceManager namespaceManager)
   at OfficeOpenXml.ExcelPackage.get_Workbook()
   at OfficeOpenXml.ExcelPackage.CreateBlankWb()
   at OfficeOpenXml.ExcelPackage.ConstructNewFile(String password)
   at OfficeOpenXml.ExcelPackage..ctor(Stream newStream)
```

**Comment by JanKallman** [comment]
Thanks for reporting this. We'll have another look at this.

**Comment by JanKallman** [comment]
This should now be fixed in EPPlus 7.0.8

**Comment by kemsky** [comment]
@JanKallman, it does not seem to be fixed in 7.0.8, maybe you meant 7.0.9?

**Comment by kemsky** [comment]
```
at System.Environment.get_StackTrace()
   at Microsoft.IO.RecyclableMemoryStream..ctor(RecyclableMemoryStreamManager memoryManager, Guid id, String tag, Int64 requestedSize, Byte[] initialLargeBuffer) in /_/src/RecyclableMemoryStream.cs:line 256
   at OfficeOpenXml.Utils.RecyclableMemory.GetStream()
   at OfficeOpenXml.OfficeProperties.GetXmlDocument(String startXml, Uri uri, String contentType, String relationship)
   at OfficeOpenXml.OfficeProperties.get_CustomPropertiesXml()
   at OfficeOpenXml.OfficeProperties..ctor(ExcelPackage package, XmlNamespaceManager ns)
   at OfficeOpenXml.ExcelWorkbook.get_Properties()
```

```
   at System.Environment.get_StackTrace()
   at Microsoft.IO.RecyclableMemoryStream..ctor(RecyclableMemoryStreamManager memoryManager, Guid id, String tag, Int64 requestedSize, Byte[] initialLargeBuffer) in /_/src/RecyclableMemoryStream.cs:line 256
   at OfficeOpenXml.Utils.RecyclableMemory.GetStream()
   at OfficeOpenXml.Packaging.ZipPackagePart.GetStream(FileMode fileMode, FileAccess fileAccess)
   at OfficeOpenXml.ExcelWorkbook.get_StylesXml()
   at OfficeOpenXml.ExcelRangeBase.get_Style()
``

**Comment by JanKallman** [comment]
Sorry for the late replay. 
These streams should be closed and disposed when you dispose the package as part of the ZipPackage.Dispose().
See https://github.com/EPPlusSoftware/EPPlus/blob/033a3db2cf5a81b2a2bfd18c771760b2e8be06f8/src/EPPlus/Packaging/ZipPackage.cs#L395
All Parts in the package is disposed here.

If this is still an issue, please re-open this issue and let me know how to reproduce this.

**Comment by kemsky** [comment]
@JanKallman, I've created sample project https://github.com/kemsky/epplus-memory-streams-1250. You can see that memory streams got finalized rather than disposed.

I don't have option to reopen.
