### ISSUE TITLE
Getting Null Exception when open file with version 7.0.6 (Works fine with 6.2.16)

### ISSUE THREAD

**Issue by kunjiangkun** [EPPlusSoftware/EPPlus#1254]
Getting Null exception when open an existing Excel file. The same file can be opened with version 6.2.16 without issue.

using (var ep = new ExcelPackage(new FileInfo(excelFile)))
{
}

   Object reference not set to an instance of an object.
   
   at OfficeOpenXml.ConditionalFormatting.ExcelConditionalFormattingContainsBlanks.UpdateFormula()
   at OfficeOpenXml.ConditionalFormatting.ExcelConditionalFormattingRule..ctor(eExcelConditionalFormattingRuleType type, ExcelAddress address, ExcelWorksheet ws, XmlReader xr)
   at OfficeOpenXml.ConditionalFormatting.ExcelConditionalFormattingRuleFactory.Create(ExcelAddress address, ExcelWorksheet ws, XmlReader xr)
   at OfficeOpenXml.ConditionalFormatting.ExcelConditionalFormattingCollection.ReadExtConditionalFormattings(XmlReader xr)
   at OfficeOpenXml.ExcelWorksheet.LoadExtLst(XmlReader xr, WorksheetZipStream stream, String& xml, String& lastXmlElement)
   at OfficeOpenXml.ExcelWorksheet.CreateXml()
   at OfficeOpenXml.ExcelWorksheet..ctor(XmlNamespaceManager ns, ExcelPackage excelPackage, String relID, Uri uriWorksheet, String sheetName, Int32 sheetID, Int32 positionID, Nullable`1 hide)
   at OfficeOpenXml.ExcelWorksheets..ctor(ExcelPackage pck, XmlNamespaceManager nsm, XmlNode topNode)
   at OfficeOpenXml.ExcelWorkbook.get_Worksheets()
   at OfficeOpenXml.ExcelWorkbook.GetDefinedNames()
   at OfficeOpenXml.ExcelPackage.get_Workbook()

**Comment by JanKallman** [comment]
Please attach a workbook to reproduce this, so we can have a look at it.

**Comment by kunjiangkun** [comment]
The issue seems to be in the conditional formatting.
[mywb.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/13953109/mywb.xlsx)

**Comment by OssianEPPlus** [comment]
This is a bug. You have conditionalformattings with #REF! as address in the worksheet. We're working on a fix.

**Comment by kunjiangkun** [comment]
Verified fix in 7.0.7.
