### ISSUE TITLE
Invalid password error for valid password

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#1255]
We have an Excel workbook that is password protected. It opens fine with Excel, but with EPPlus an "Invalid password" error is thrown. Stacktrace below. I attached the workbook. The valid password is "fayneuberger1!"

   at OfficeOpenXml.Encryption.EncryptedPackageHandler.DecryptAgile(EncryptionInfoAgile encryptionInfo, String password, Int64 size, Byte[] encryptedData, Byte[] data)
   at OfficeOpenXml.Encryption.EncryptedPackageHandler.DecryptDocument(Byte[] data, EncryptionInfo encryptionInfo, String password)
   at OfficeOpenXml.Encryption.EncryptedPackageHandler.GetStreamFromPackage(CompoundDocument doc, ExcelEncryption encryption)
   at OfficeOpenXml.Encryption.EncryptedPackageHandler.DecryptPackage(MemoryStream stream, ExcelEncryption encryption)
   at OfficeOpenXml.ExcelPackage.Load(Stream input, Stream output, String Password)
   at OfficeOpenXml.ExcelPackage.Load(Stream input, String Password)

**Comment by JanKallman** [comment]
Can you attach the workbook?

**Comment by rdhasse** [comment]
I attached the workbook to support ticket 590

**Comment by swmal** [comment]
Fixed in the latest version of EPPlus 7
