### ISSUE TITLE
Getting XmlException when trying to access ExcelPackage's Workbook

### ISSUE THREAD

**Issue by 25Ericcheong** [EPPlusSoftware/EPPlus#1359]
Hi, 

Recently we upgraded to EPPlus's version 7.0.8. We were originally on version 5.3.1 and this has never happened before (it started only after the upgrade to version 7.0.8)

This doesn't happen to all files but only to some specific `.xlsx` files. After further investigation I realize that removing a specific worksheet helped resolve the issue, but I can't seem to find what is wrong specifically with the sheet as I am unable to reproduce the error with a new excel file.

Was hoping if I could find out if any changes were made based on the stacktrace below

```
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at OfficeOpenXml.Utils.XmlReaderHelper.ReadUntil(XmlReader xr, Int32 depth, String[] tagName)
   at OfficeOpenXml.ExcelWorksheet.LoadColumns(XmlReader xr)
   at OfficeOpenXml.ExcelWorksheet.CreateXml()
   at OfficeOpenXml.ExcelWorksheet..ctor(XmlNamespaceManager ns, ExcelPackage excelPackage, String relID, Uri uriWorksheet, String sheetName, Int32 sheetID, Int32 positionID, Nullable`1 hide)
   at OfficeOpenXml.ExcelWorksheets..ctor(ExcelPackage pck, XmlNamespaceManager nsm, XmlNode topNode)
   at OfficeOpenXml.ExcelWorkbook.get_Worksheets()
   at OfficeOpenXml.ExcelWorkbook.GetDefinedNames()
   at OfficeOpenXml.ExcelPackage.get_Workbook()
```

From what I can tell while debugging (this is a runtime error), I realize that the error originated from the following code when I am trying to access the `Worksheets` property within the `ExcelWorkbook.cs` file

```
public ExcelWorksheets Worksheets
    {
      get
      {
        if (this._worksheets == null)
          this._worksheets = new ExcelWorksheets(this._package, this._namespaceManager, this._workbookXml.DocumentElement.SelectSingleNode("d:sheets", this._namespaceManager) ?? this.CreateNode("d:sheets"));
        return this._worksheets;
      }
    }
``` 

This is how I am currently calling the `.Worksheet` property in my code

```
var fileMemoryTest = new MemoryStream(uploadedBytes);
var packageTest = new ExcelPackage(fileMemoryTest);
var worksheetsTest = packageTest.Workbook; // runtime error occurs here
```

Due to the sensitivity of the data, I am unable to provide the original Excel file but I am hoping to find out if anything has changed in terms of parsing and encoding the XML files which I suspect is the cause of this since it was working fine in version 5.3.1 but started when we upgraded to version 7.0.8

Thank you, do let me know if I can provide more information.

**Comment by JanKallman** [comment]
I cant tell what is going wrong without having a workbook to reproduce the issue. If you have a commercial license you can upload your workbook in our support portal at our website.

**Comment by JanKallman** [comment]
See #1362
