### ISSUE TITLE
NullReferenceException in CopyDxfStylesTables

### ISSUE THREAD

**Issue by PatrickvL** [EPPlusSoftware/EPPlus#1600]
### EPPlus usage

Noncommercial use

### Environment

WIndows

### Epplus version

7.3.2

### Description

Similar to #1597, another `NullReferenceException` happens when copying sheets from one ExcelPackage to another, using this code:
```
ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
using ExcelPackage publishedPackage = ExcelPackage new NewExcelPackage(new FileInfo(excelFileName));
// Copy the sheets added to the Complete report up until now.
foreach (ExcelWorksheet completeSheet in workbook.Worksheets)
{
    Logger.Log("    Copying sheet: " + completeSheet.Name);
    // This is significantly faster compared to creating and populating all preceding sheets twice.
    publishedPackage.Workbook.Worksheets.Add(completeSheet.Name, completeSheet);
}
```
The exception has this call stack:
```
   at OfficeOpenXml.Core.Worksheet.WorksheetCopyHelper.CopyDxfStylesTables(ExcelWorksheet copy, ExcelWorksheet added)
   at OfficeOpenXml.Core.Worksheet.WorksheetCopyHelper.CopyDxfStyles(ExcelWorksheet copy, ExcelWorksheet added)
   at OfficeOpenXml.Core.Worksheet.WorksheetCopyHelper.CloneCellsAndStyles(ExcelWorksheet Copy, ExcelWorksheet added)
   at OfficeOpenXml.Core.Worksheet.WorksheetCopyHelper.Copy(ExcelWorksheets targetWorksheets, String name, ExcelWorksheet sourceWorksheet)
   at OfficeOpenXml.ExcelWorksheets.Add(String Name, ExcelWorksheet Copy)
```
   
This happens on below last line, because `excelTable2` is `null`:
```
for (int j = 0; j < excelTable.Columns.Count; j++)
{
    ExcelTableColumn excelTableColumn = excelTable.Columns[j];
    ExcelTableColumn excelTableColumn2 = excelTable2.Columns[j]; // <-- NullReferenceException !
```
The likely reason it becomes null, is because the assignment looks like this:
`ExcelTable excelTable2 = added.Tables[excelTable.Name];`
while the preceding line assign the  source like this:
`ExcelTable excelTable = copy.Tables[i];`

So, perhaps merely changing the offending line into this might solve it?
``ExcelTable excelTable2 = added.Tables[i];`

**Comment by PatrickvL** [comment]
An important note : The above happens when the source sheets are populated in a `Task.Run()` delegate (that receives as an argument, the result of a `(ExcelWorkbook)workbook.Worksheet.Add(title)` call in the main thread.

When the sheets have been populated sequentially in the main thread (without a `Task.Run()` delegate), the exception does not occur!

**Comment by PatrickvL** [comment]
Another note : `LoadFromCollection` turns out to suffer from a race-condition too, when ran parallely via `Task.Run()` delegates, even when targetting just a single ExcelPackage, and even when the WorkSheets have been created in the main worker thread. This specific race-condition happens in with this call stack:
```
System.Private.CoreLib.dll!System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException<System.__Canon>(System.__Canon key)
System.Private.CoreLib.dll!System.Collections.Generic.Dictionary<string, int>.TryInsert(string key, int value, System.Collections.Generic.InsertionBehavior behavior)
EPPlus.dll!OfficeOpenXml.ExcelStyleCollection<OfficeOpenXml.Style.XmlAccess.ExcelXfs>.Add(string key, OfficeOpenXml.Style.XmlAccess.ExcelXfs item)
EPPlus.dll!OfficeOpenXml.ExcelStyles.SetStyleCells(OfficeOpenXml.Style.StyleBase sender, OfficeOpenXml.Style.StyleChangeEventArgs e, OfficeOpenXml.ExcelAddressBase address, OfficeOpenXml.ExcelWorksheet ws, System.Collections.Generic.Dictionary<int, int> styleCashe)
EPPlus.dll!OfficeOpenXml.ExcelStyles.SetStyleAddress(OfficeOpenXml.Style.StyleBase sender, OfficeOpenXml.Style.StyleChangeEventArgs e, OfficeOpenXml.ExcelAddressBase address, OfficeOpenXml.ExcelWorksheet ws, ref System.Collections.Generic.Dictionary<int, int> styleCashe)
EPPlus.dll!OfficeOpenXml.ExcelStyles.PropertyChange(OfficeOpenXml.Style.StyleBase sender, OfficeOpenXml.Style.StyleChangeEventArgs e)
EPPlus.dll!OfficeOpenXml.Style.ExcelNumberFormat.Format.set(string value)
EPPlus.dll!OfficeOpenXml.Table.ExcelTableDxfBase.SetHeaderStyle(OfficeOpenXml.Style.eStyleClass styleClass, OfficeOpenXml.Style.eStyleProperty styleProperty, object value)
EPPlus.dll!OfficeOpenXml.Style.Dxf.ExcelDxfStyle.SetStyle()
EPPlus.dll!OfficeOpenXml.Table.ExcelTable.ShowHeader.set(bool value)
EPPlus.dll!OfficeOpenXml.LoadFunctions.LoadFunctionBase.Load()
```

EDIT : Above call stack applies to older EPPlus version, 6.2.7 - newer version 7.3.2 doesn't seem to suffer from this particular problem.

However, even with the newer version, updating styles in parallel still causes damaged output, as opening the resulting file in Excel leads to a recoveryLog like this:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
	<logFileName>error167840_02.xml</logFileName>
	<summary>Errors were detected in file 'D:\whatever_filename.xlsx'</summary>
	<repairedRecords>
		<repairedRecord>Repaired Records: Table from /xl/tables/table1.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table2.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table3.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table4.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table5.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table6.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table7.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table8.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table9.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table10.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table11.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table12.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table13.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table14.xml part (Table)</repairedRecord>
		<repairedRecord>Repaired Records: Table from /xl/tables/table15.xml part (Table)</repairedRecord>
		<repairedRecord xml:space="preserve">Repaired Records: Table from /xl/tables/table16.xml part </repairedRecord>
		<repairedRecord>Repaired Records: T</repairedRecord>
		<repairedRecord>Repaired Records: T</repairedRecord>
		<repairedRecord>Repaired Records: T</repairedRecord>
		<repairedRecord>Repaired Records: T</repairedRecord>
		<repairedRecord>Repaired Records: T</repairedRecord>
		<repairedRecord xml:space="preserve">Repaired Records: </repairedRecord>
	</repairedRecords>
</recoveryLog>
```

EDIT 2 : Should this issue be split in 3 separate ones, given it's now describing 3 problems? (Although they are all related to multi-threaded updates to worksheet styles, so perhaps updating the title suffices.)

**Comment by JanKallman** [comment]
Can you attach the workbook you are using, so we can reproduce the first issue?
When it comes to thread-safety, note that EPPlus is currently not thread safe when you run multiple threads against the same package. 
This is something we will address in coming versions. Feel free to add issues when this does not work, so we can start fixing these issues.

**Comment by JanKallman** [comment]
Closed due to no response
