### ISSUE TITLE
 ExcelPackage.GetAsByteArray() gives an error for v5.4

### ISSUE THREAD

**Issue by igigiberia** [EPPlusSoftware/EPPlus#198]
I have tested for 5.3.2, it works fine.
When I upgrade to 5.4, it gives an error:
"An item with the same key has already been added."

**Comment by JanKallman** [comment]
Can you provide a reproducable sample?

**Comment by JanKallman** [comment]
Can't reproduce, feel free to re-open with a reproducable sample

**Comment by igigiberia** [comment]
I could share the session, but code is quite big and it's not easy to provide an example, as it works over the report that is auto generated.
I have referenced the latest code cloned instead of nuget, and this is exact exception what I get:

System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at OfficeOpenXml.Table.PivotTable.ExcelPivotTableCacheField.UpdateCacheLookupFromItems(List`1 items) in E:\Repos\EPPlus\src\EPPlus\Table\PivotTable\ExcelPivotTableCacheField.cs:line 699

  This exception was originally thrown at this call stack:
    [External Code]
    OfficeOpenXml.Table.PivotTable.ExcelPivotTableCacheField.UpdateCacheLookupFromItems(System.Collections.Generic.List<object>) in ExcelPivotTableCacheField.cs
