### ISSUE TITLE
Null dereference exception while saving existing workbook after writing with EPPlus

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#296]
Hello,

Using EPPlus 5.5.2, we are observing the below null dereference exception while saving an existing workbook after writing with EPPlus: System.NullReferenceException: Object reference not set to an instance of an object. 

### Stack trace:
   at OfficeOpenXml.Table.PivotTable.PivotTableCacheInternal.RefreshFields()
   at OfficeOpenXml.ExcelWorkbook.FixFieldNamesAndUpdateSharedItems(PivotTableCacheInternal cache, ExcelTable t, XmlNodeList fields)
   at OfficeOpenXml.ExcelWorkbook.SavePivotTableCaches()
   at OfficeOpenXml.ExcelWorkbook.Save()
   at OfficeOpenXml.ExcelPackage.GetAsByteArray(Boolean save)
   at nb.Office.Excel.WorkBook.SaveAs(String fileName)
   at nb.Engine.DataTransfer.StepProcessors.WriteExcelStep.Process(Int32 attempt) in C:\source\nb.Web.Site\nb.Web.Site\nb.Engine.DataTransfer\StepProcessors\WriteExcelStep.cs:line 198
   at nb.Engine.DataTransfer.StepProcessors.WriteExcelStep.Process(LinkedListNode`1 stepNode) in C:\source\nb.Web.Site\nb.Web.Site\nb.Engine.DataTransfer\StepProcessors\WriteExcelStep.cs:line 94
   at nb.Engine.DataTransfer.Data.Process.ProcessNode(LinkedListNode`1 n) in C:\source\nb.Web.Site\nb.Web.Site\nb.Engine.DataTransfer\Data\Process.cs:line 203

### Below summarizes what we are doing with the workbook:
ExcelWorksheet ws = wb.Worksheets.Add(name);
//then write some data to the new worksheet
wb.SaveAs(filename) //exception thrown here

**Comment by rdhasse** [comment]
[test_excel_workbook_before2.zip](https://github.com/EPPlusSoftware/EPPlus/files/5906695/test_excel_workbook_before2.zip)

**Comment by JanKallman** [comment]
This issue is fixed and will go into 5.5.3 shortly. Please verify using latest develop build.

**Comment by JanKallman** [comment]
Fixed in 5.5.3
