### ISSUE TITLE
Null dereference exception while writing existing workbook

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#297]
This occurred when writing to an existing workbook (not while saving).   Unfortunately, it seems to not be consistently reproducible.  If I can determine a consistent way to reproduce I'll attach those steps and/or the file.  Stacktrace below.

### Stacktrace:

   at OfficeOpenXml.ExcelRangeBase..ctor(ExcelWorksheet xlWorksheet, String address)
   at OfficeOpenXml.ExcelNamedRangeCollection.AddName(String Name, ExcelRangeBase Range)
   at OfficeOpenXml.ExcelWorkbook.GetDefinedNames()
   at OfficeOpenXml.ExcelPackage.get_Workbook()
   at nb.Office.Excel.WorkBook.get_Sheets()
   at nb.Office.Excel.WorkBook.WriteDataTableToRange(String sheetName, DataTable dt, String destCellRange, Int32 numberHeaderRows)
   at nb.Engine.DataTransfer.StepProcessors.WriteExcelStep.Process(Int32 attempt) in C:\source\nb.Web.Site\nb.Web.Site\nb.Engine.DataTransfer\StepProcessors\WriteExcelStep.cs:line 260
   at nb.Engine.DataTransfer.StepProcessors.WriteExcelStep.Process(LinkedListNode`1 stepNode) in C:\source\nb.Web.Site\nb.Web.Site\nb.Engine.DataTransfer\StepProcessors\WriteExcelStep.cs:line 94
   at nb.Engine.DataTransfer.Data.Process.ProcessNode(LinkedListNode`1 n) in C:\source\nb.Web.Site\nb.Web.Site\nb.Engine.DataTransfer\Data\Process.cs:line 203

**Comment by JanKallman** [comment]
Hard to see why it happens using the stack trace only. Let me know if you can reproduce.

**Comment by JanKallman** [comment]
I'll close this issue for now. Feel free to reopen the issue if you can reproduce the exception.
