### ISSUE TITLE
Enumerating drawings is not thread safe

### ISSUE THREAD

**Issue by leecannon** [EPPlusSoftware/EPPlus#367]
Due to the changes in https://github.com/EPPlusSoftware/EPPlus/commit/219e8b443db6848c8db06051ae3777869d5f7113 enumerating drawings on different threads is not thread safe, even if the threads each have their own `ExcelPackage` each with a different file open as the dictionaries used are static and therefore shared application wide.

For example the code below has multiple issues:
- If two threads both check for the key on line 664 and find that it is not present they will both try to add the same key on line 666 causing a `ArgumentException`
- As seen in the real example error below, it is possible that one thread (t1) will see a key present on line 664 then another thread (t2) clears the cache by calling `ResetWidthRowCache()` before t1 executes line 668 causing a `KeyNotFoundException`

https://github.com/EPPlusSoftware/EPPlus/blob/a1b2db7fce8488ef6e9aa7a36ac3a7bc2ee47502/src/EPPlus/Drawing/ExcelDrawing.cs#L664-L668 

In general the issue is much worse as *all* `ExcelDrawings` irregardless of if they are on the same workbook/worksheet share the same static row/column cache which means it is easy for the cache to be wrong for a specific drawing as the cache may contain data for a completely different worksheet.

To get around this in my application I have been forced to add a global static lock which always has to be held when doing anything with `ExcelDrawing`s

## An example error is:
```
System.Collections.Generic.KeyNotFoundException: The given key '0' was not present in the dictionary.
       at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
       at OfficeOpenXml.Drawing.ExcelDrawing.GetPixelTop()
       at OfficeOpenXml.Drawing.ExcelDrawing.GetPositionSize()
       at OfficeOpenXml.Drawing.ExcelDrawing..ctor(ExcelDrawings drawings, XmlNode node, String topPath, String nvPrPath, ExcelGroupShape parent)
       at OfficeOpenXml.Drawing.Chart.ExcelChartStandard..ctor(ExcelDrawings drawings, XmlNode node, Uri uriChart, ZipPackagePart part, XmlDocument chartXml, XmlNode chartNode, ExcelGroupShape parent, String drawingPath, String nvPrPath)
       at OfficeOpenXml.Drawing.Chart.ExcelChart.GetChart(XmlElement chartNode, ExcelDrawings drawings, XmlNode node, Uri uriChart, ZipPackagePart part, XmlDocument chartXml, ExcelChart topChart, ExcelGroupShape parent)
       at OfficeOpenXml.Drawing.Chart.ExcelChart.CreateChartFromXml(ExcelDrawings drawings, XmlNode node, Uri uriChart, ZipPackagePart part, XmlDocument chartXml, ExcelGroupShape parent)
       at OfficeOpenXml.Drawing.Chart.ExcelChart.GetChart(ExcelDrawings drawings, XmlNode node, ExcelGroupShape parent)
       at OfficeOpenXml.Drawing.ExcelDrawing.GetDrawingFromNode(ExcelDrawings drawings, XmlNode node, XmlElement drawNode, ExcelGroupShape parent)
       at OfficeOpenXml.Drawing.ExcelDrawing.GetDrawing(ExcelDrawings drawings, XmlNode node)
       at OfficeOpenXml.Drawing.ExcelDrawings.AddDrawings()
       at OfficeOpenXml.Drawing.ExcelDrawings..ctor(ExcelPackage xlPackage, ExcelWorksheet sheet)
       at OfficeOpenXml.ExcelWorksheet.get_Drawings()
```

**Comment by JanKallman** [comment]
The `_rowHeights` should not be static. I'll add a correction for this and set a lock around the adding of the row height.

**Comment by JanKallman** [comment]
Try the fix provided and let me know if it works correctly for you.

**Comment by leecannon** [comment]
Yp this looks like it fixed it.
