### ISSUE TITLE
Copying a worksheet containing a wmf image throws an exception in Linux

### ISSUE THREAD

**Issue by craigbrown** [EPPlusSoftware/EPPlus#494]
See the attached workbook, which is an example of a sheet containing a .wmf image file. If you try to copy this worksheet into a new workbook on Linux, you get an exception:

```
System.ArgumentException: Parameter is not valid.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at System.Drawing.Image.Save(Stream stream, ImageFormat format)
   at OfficeOpenXml.Compatibility.ImageCompat.GetImageAsByteArray(Image image)
   at OfficeOpenXml.Drawing.ExcelPicture..ctor(ExcelDrawings drawings, XmlNode node, ExcelGroupShape shape)
   at OfficeOpenXml.Drawing.ExcelDrawing.GetDrawingFromNode(ExcelDrawings drawings, XmlNode node, XmlElement drawNode, ExcelGroupShape parent)
   at OfficeOpenXml.Drawing.ExcelDrawing.GetDrawing(ExcelDrawings drawings, XmlNode node)
   at OfficeOpenXml.Drawing.ExcelDrawings.AddDrawings()
   at OfficeOpenXml.Drawing.ExcelDrawings..ctor(ExcelPackage xlPackage, ExcelWorksheet sheet)
   at OfficeOpenXml.Core.Worksheet.WorksheetCopyHelper.CopyDrawing(ExcelPackage pck, XmlNamespaceManager nsm, ExcelWorksheet Copy, ExcelWorksheet added)
   at OfficeOpenXml.Core.Worksheet.WorksheetCopyHelper.Copy(ExcelWorksheets worksheets, String name, ExcelWorksheet copy)
   at OfficeOpenXml.ExcelWorksheets.Add(String Name, ExcelWorksheet Copy)
   at CmdAppDemo.Commands.CopyWorksheet.Execute(FileInfo sourceWorkbook, FileInfo targetWorkbook, String worksheetName)
```

This is _with_ the `libgdiplus` package installed. I guess this is because `libgdiplus` [doesn't have support](https://github.com/mono/libgdiplus/blob/main/src/image.c#L2317) for wmf/emf files. I tested this with a workbook containing a jpeg, and that worked fine.

This isn't a huge deal for us as the wmf images in our workbooks weren't important so we've just deleted the images. But I thought I'd report this anyway, so you know about it.

[WbkContainingWmf.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/7198790/WbkContainingWmf.xlsx)

**Comment by JanKallman** [comment]
Thanks, yes, this is a known issue/limitation when using non-windows systems and Windows Nano server (which totally misses GDI)...
https://github.com/EPPlusSoftware/EPPlus/wiki/Shapes,-Pictures,-Controls-and-Charts#pictures

**Comment by craigbrown** [comment]
Ah ok thanks, I hadn't seen that.
