### ISSUE TITLE
The given key was not present in the dictionary

### ISSUE THREAD

**Issue by oalmaraz** [EPPlusSoftware/EPPlus#507]
Hello, I'm using EPPlus 5.7.5
I created a new project where I tried to open an excel file downloaded from a customer site.
This file has cells with links.
When I try to get the Worksheet, I'm getting the message 'The given key was not present in the dictionary'.

System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key was not present in the dictionary.
  Source=mscorlib
  StackTrace:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OfficeOpenXml.ExcelWorksheet.LoadHyperLinks(XmlReader xr)
   at OfficeOpenXml.ExcelWorksheet.CreateXml()
   at OfficeOpenXml.ExcelWorksheet..ctor(XmlNamespaceManager ns, ExcelPackage excelPackage, String relID, Uri uriWorksheet, String sheetName, Int32 sheetID, Int32 positionID, Nullable`1 hide)
   at OfficeOpenXml.ExcelWorksheets..ctor(ExcelPackage pck, XmlNamespaceManager nsm, XmlNode topNode)
   at OfficeOpenXml.ExcelWorkbook.get_Worksheets()
   at WindowsFormsApp.Form1.btnTest_Click(Object sender, EventArgs e) in C:\Users\oswald\source\repos\WindowsFormsApp\WindowsFormsApp\Form1.cs:line 33
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at WindowsFormsApp.Program.Main() in C:\Users\oswald\source\repos\WindowsFormsApp\WindowsFormsApp\Program.cs:line 19

  This exception was originally thrown at this call stack:
    [External Code]
    WindowsFormsApp.Form1.btnTest_Click(object, System.EventArgs) in Form1.cs
    [External Code]
    WindowsFormsApp.Program.Main() in Program.cs

--------------------------

Debugging the EPPlus code I found that in the ExcelWorksheet class in the LoadHyperLinks function fails getting the id, in line:
Part.GetRelationship(rId);
and it raises the above error. The count of items with hyperLinks is equal to 0 (I reviewed Part.GetRelationships().Count )

If I open the file using Excel and save it without doing anything else, the error is fixed and EPPlus can open the file. 
With this new file  Part.GetRelationships().Count is mayor than 0 and Part.GetRelationship(rId); works fine.

This error could be solved in the LoadHyperLinks function by validating the number of items before trying to access the data.

What do you think about this?

**Comment by JanKallman** [comment]
Can you attach the xlsx file that reproduces this issue?

**Comment by oalmaraz** [comment]
I was unable to obtain authorization from the client to share the file. 
I'm trying to recreate the file with the same problem so that I can add it to this issue.

**Comment by oalmaraz** [comment]
I'm going to close the issue because I couldn't reproduce the error when creating a new excel file.
