### ISSUE TITLE
Parameter is not valid.

### ISSUE THREAD

**Issue by 93910676wangd** [EPPlusSoftware/EPPlus#577]
Hi, after opening the attachment file.xlsx with epplus, the following error occurred when calling the excelPackage.**GetAsByteArray**(); method,

"-2147024809","**Parameter is not valid.**",,"2022/01/12","05:48:39","   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at System.Drawing.Image.Save(Stream stream, ImageFormat format)
   at OfficeOpenXml.Compatibility.ImageCompat.GetImageAsByteArray(Image image)
   at OfficeOpenXml.Drawing.ExcelPicture..ctor(ExcelDrawings drawings, XmlNode node, ExcelGroupShape shape)
   at OfficeOpenXml.Drawing.ExcelDrawing.GetDrawing(ExcelDrawings drawings, XmlNode node)
   at OfficeOpenXml.Drawing.ExcelDrawings.AddDrawings()
   at OfficeOpenXml.ExcelWorksheet.Save()
   at OfficeOpenXml.ExcelWorkbook.Save()
   at OfficeOpenXml.ExcelPackage.Save()

How to solve this problem? Is it epplus bug? thanks 

epplus:5.3.2
centos:7.9

[file.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/7887068/file.xlsx)

**Comment by 93910676wangd** [comment]
Ps:
It is normally executed under window OS
look forward to your explanation

**Comment by 93910676wangd** [comment]
The EMF figure contains the EMF figure.

The conversion failed because epplus under linux environment does not support the type of figure.
