### ISSUE TITLE
Save failed: The given key was not present in the dictionary

### ISSUE THREAD

**Issue by celeong** [EPPlusSoftware/EPPlus#592]
I am opening an existing xlsx file as a template, and then save it as another copy.
When I call `Save()`, an InvalidOperationException occurs.

I have attached the offending file.
I have removed almost all data and drawings, and I still can reproduce this bug.

Note:
I have also drilled down to the offending code. 
When I enumerate the ExcelWorksheet.Drawings, I will get the same exception.
But if I handle the exception in a try..catch block, I can save the file.
I think the issue is inside the enumeration of the Drawings not handling some special case.

Stack trace:
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OfficeOpenXml.Style.XmlAccess.ExcelFontXml.GetHeightByName(String name, Single size)
   at OfficeOpenXml.Style.XmlAccess.ExcelFontXml.GetFontHeight(String name, Single size)
   at OfficeOpenXml.ExcelWorksheet.GetRowHeightFromCellFonts(Int32 row)
   at OfficeOpenXml.ExcelWorksheet.GetRowHeight(Int32 row)
   at OfficeOpenXml.Drawing.ExcelDrawing.GetPixelTop()
   at OfficeOpenXml.Drawing.ExcelDrawing.GetPositionSize()
   at OfficeOpenXml.Drawing.ExcelDrawing..ctor(ExcelDrawings drawings, XmlNode node, String topPath, String nvPrPath, ExcelGroupShape parent)
   at OfficeOpenXml.Drawing.ExcelShapeBase..ctor(ExcelDrawings drawings, XmlNode node, String topPath, String nvPrPath, ExcelGroupShape parent)
   at OfficeOpenXml.Drawing.ExcelDrawing.GetShapeOrControl(ExcelDrawings drawings, XmlNode node, XmlElement drawNode, ExcelGroupShape parent)
   at OfficeOpenXml.Drawing.ExcelDrawing.GetDrawingFromNode(ExcelDrawings drawings, XmlNode node, XmlElement drawNode, ExcelGroupShape parent)
   at OfficeOpenXml.Drawing.ExcelDrawing.GetDrawing(ExcelDrawings drawings, XmlNode node)
   at OfficeOpenXml.Drawing.ExcelDrawings.AddDrawings()
   at OfficeOpenXml.Drawing.ExcelDrawings..ctor(ExcelPackage xlPackage, ExcelWorksheet sheet)
   at OfficeOpenXml.ExcelWorksheet.SaveDrawings()
   at OfficeOpenXml.ExcelWorksheet.Save()
   at OfficeOpenXml.ExcelWorkbook.Save()
   at OfficeOpenXml.ExcelPackage.Save()
[test.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/8037520/test.xlsx)

**Comment by JanKallman** [comment]
This issue should be fixed in version 5.8.7
