### ISSUE TITLE
Unable to open Excel File:  The given key 'rId28' was not present in the dictionary

### ISSUE THREAD

**Issue by imrantahir0092** [EPPlusSoftware/EPPlus#596]
I have a parser trying to open an Excel file sent by a client.  I believe the file was originally saved in an older version of office.

- If I open and save the file again, then the error goes away and data can be imported.

On running the following line, I am getting "KeyNotFoundException":

- ExcelWorksheet firstWorksheet = excelPackage.Workbook.Worksheets[0];

The stack error message is:

System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key 'rId28' was not present in the dictionary.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OfficeOpenXml.ExcelWorksheet.LoadHyperLinks(XmlReader xr)
   at OfficeOpenXml.ExcelWorksheet.CreateXml()
   at OfficeOpenXml.ExcelWorksheet..ctor(XmlNamespaceManager ns, ExcelPackage excelPackage, String relID, Uri uriWorksheet, String sheetName, Int32 sheetID, Int32 positionID, Nullable`1 hide)
   at OfficeOpenXml.ExcelWorksheets..ctor(ExcelPackage pck, XmlNamespaceManager nsm, XmlNode topNode)
   at OfficeOpenXml.ExcelWorkbook.get_Worksheets()
   at OfficeOpenXml.ExcelWorkbook.GetDefinedNames()
   at OfficeOpenXml.ExcelPackage.get_Workbook()
   at ExcelTest.Program.EPPlus() in C:\ExcelTest\ExcelTest\Program.cs:line 30
   at ExcelTest.Program.Main(String[] args) in C:\ExcelTest\ExcelTest\Program.cs:line 13

Additional Info:

- There are some Hidden URL links in the Excel File
- There are some references to "rId28" in the "sheet1.xml" and "sheet1.xml.rels" files

Thanks

**Comment by JanKallman** [comment]
Can you attach the xlsx file?

**Comment by imrantahir0092** [comment]
Hi,
Can I upload the file into a private folder OR email it directly to you so that it is not in the public domain?  
Thanks

**Comment by JanKallman** [comment]
If you have a commercial license, please create a support case on our web site and upload the workbook there.

**Comment by JanKallman** [comment]
EPPlus failed to load if more than one hyperlink refereed to the same external relation.

**Comment by JanKallman** [comment]
Fixed in version 5.8.7
