### ISSUE TITLE
System.OutOfMemoryException EPPlus (5.8.8)

### ISSUE THREAD

**Issue by anaratz** [EPPlusSoftware/EPPlus#617]
Hi,
We are getting an OutOfMemory exception from EPPlus in our production environment, when we try to generate an Excel document of around 180,000 rows.
The issue only happens in Production.
The production server hardware should be sufficient (in our view). 
It is a Microsoft Azure P2V3 virtual machine with 16GB of memory. It is also X64

We are using the latest stable version of EPPlus (5.8.8)

As far as we can tell, EPPlus seems to build everything in memory until you call package.save() at which point it is written to disk?
Is there a way for example to save to disk say every 50,000 rows (free up some memory) then continue, or some other best practise we can adopt here? Any thoughts / help would be appreciated.

The stack trace is:
`Failed to get data.Exception of type 'System.OutOfMemoryException' was thrown. stack: at System.Collections.Generic.List`1.set_Capacity(Int32 value)
at System.Collections.Generic.List`1.Grow(Int32 capacity)
   at System.Collections.Generic.List`1.AddWithResize(T item)
   at OfficeOpenXml.Core.CellStore.CellStore`1.SetValueColumn(Int32 row, Int32 column, T value, Int32 colPos)
   at OfficeOpenXml.Core.CellStore.CellStore`1.SetValue(Int32 row, Int32 column, T value)   at OfficeOpenXml.Core.CellStore.CellStoreValue.SetValue_Value(Int32 Row, Int32 Column, Object value)
   at OfficeOpenXml.ExcelRangeBase.Set_Value(ExcelRangeBase range, Object value, Int32 row, Int32 col)
   at OfficeOpenXml.ExcelRangeBase.SetSingle(ExcelRangeBase range, _setValue valueMethod, Object value)`

**Comment by JanKallman** [comment]
No, there is no way to save rows in blocks. 180k rows is a lot if you have many columns and it also depends on the size of the data and the styling. Note that the size of the saved package is zipped, so the size of the underlaying xml will be many times larger.
Also, make sure that your application/component builds for x64 and that you don't have the prefer 32-bit checkbox set.
