### ISSUE TITLE
Using EPPlus 5's async overloads still using synchronous IO

### ISSUE THREAD

**Issue by onionhammer** [EPPlusSoftware/EPPlus#69]
CopyStreamAsync still using synchronous IO

```
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Flush()
   at OfficeOpenXml.ExcelPackage.CopyStreamAsync(Stream inputStream, Stream outputStream)
   at OfficeOpenXml.ExcelPackage.SaveAsAsync(Stream OutputStream)
```

**Comment by swmal** [comment]
Thanks for reporting!

This is fixed in the next version that will be released on Nuget very soon. The call to Flush() has been changed to FlushAsync().

Here is a link to the commit:

https://github.com/EPPlusSoftware/EPPlus/commit/7cb01f28d5a6d5f75a8a11e5627a13b1b1eac875#diff-9573cbdaa327d5c052d61ba7b8eab519
