### ISSUE TITLE
Error "Nullable object must have a value" while saving the excelPackage object

### ISSUE THREAD

**Issue by satishreddyv** [EPPlusSoftware/EPPlus#707]
Hello,
Getting the below error while saving the stream back to the sheet stored on SharePoint Online. Surprisingly, the error wont show up after manually opening the excel file in Excel online and closing it. It looks like there is some auto correction happening once I open the file in Excel online. I tried ignoring the errors as well, but no luck. Please help me.

Nullable object must have a value.
 at System.Nullable`1.get_Value()
 at OfficeOpenXml.Style.XmlAccess.ExcelColorXml.CreateXmlNode(XmlNode topNode)
 at OfficeOpenXml.Style.XmlAccess.ExcelBorderItemXml.CreateXmlNode(XmlNode topNode)
 at OfficeOpenXml.Style.XmlAccess.ExcelBorderXml.CreateXmlNode(XmlNode topNode)
 at OfficeOpenXml.ExcelStyles.UpdateBorderXml()
 at OfficeOpenXml.ExcelStyles.UpdateXml()
 at OfficeOpenXml.ExcelWorkbook.Save()
 at OfficeOpenXml.ExcelPackage.Save()

**Comment by JanKallman** [comment]
Please provide some code and a workbook, if necessary, to reproduce this issue.

**Comment by satishreddyv** [comment]
Thanks for the reply. I have sent a console app and workbook via email (to info email).

**Comment by JanKallman** [comment]
I just noticed that your mail got caught by our spam filter, so I did not see it until now. This seems to occur on color elements with the auto attribute set to false and no other attributes. I have added fix for it. Feel free to try it using latest develop build... https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-Develop-Nuget-Feed

**Comment by JanKallman** [comment]
Fixed in EPPlus 6.1
