### ISSUE TITLE
Exception while reading file

### ISSUE THREAD

**Issue by rdhasse** [EPPlusSoftware/EPPlus#742]
Hello,

We have an Excel file that throws the below exception when reading with EPPlus.  Please provide an email where I can send the file where this exception occurs.  I can't attach it here as it contains sensitive data.

### Exception Message:
Input string was not in a correct format.

### Exception Stacktrace:
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s, NumberStyles style, IFormatProvider provider)
   at System.Xml.XmlReader.ReadElementContentAsInt()
   at OfficeOpenXml.Utils.ConvertUtil.GetValueFromType(XmlReader xr, String type, Int32 styleId, ExcelWorkbook workbook)
   at OfficeOpenXml.ExcelWorksheet.SetValueFromXml(XmlReader xr, String type, Int32 styleID, Int32 row, Int32 col)
   at OfficeOpenXml.ExcelWorksheet.LoadCells(XmlReader xr)
   at OfficeOpenXml.ExcelWorksheet.CreateXml()
   at OfficeOpenXml.ExcelWorksheet..ctor(XmlNamespaceManager ns, ExcelPackage excelPackage, String relID, Uri uriWorksheet, String sheetName, Int32 sheetID, Int32 positionID, Nullable`1 hide)
   at OfficeOpenXml.ExcelWorksheets..ctor(ExcelPackage pck, XmlNamespaceManager nsm, XmlNode topNode)
   at OfficeOpenXml.ExcelWorkbook.get_Worksheets()

**Comment by JanKallman** [comment]
Hello,
Send it to me or to our info email-address

**Comment by JanKallman** [comment]
This happens when a cell value (the c-element) contains a type "s" (shared string) but does not contain an integer reference to the shared string table. This is apparently valid if the v elements content is empty:
```Xml
<c r="A1" t="s" s="1">
  <v><v/>
</c>
```
I will provide a fix shortly.

**Comment by JanKallman** [comment]
This is fixed in EPPlus 6.1.1
