### ISSUE TITLE
Issue With Scientific Notation in IF Formula

### ISSUE THREAD

**Issue by johnmiller86** [EPPlusSoftware/EPPlus#870]
I stumbled across #797 when researching the issue I'm seeing.  Our UW department provided us with a new template file that uses Scientific Notation for assignment within an IF function.

Formula:
```
IF(B21 = "Active",  IF(Maximum_Q2 = "Unlimited", 9E+50, Maximum_Q2), 0)
```

Logged Error:
```
Worksheet: Plan Design Factor
Address: M18
OfficeOpenXml.FormulaParsing.Exceptions.ExcelErrorValueException: #NAME?
   at OfficeOpenXml.FormulaParsing.Excel.Functions.DoubleEnumerableArgConverter.<>c__DisplayClass0_0.<ConvertArgs>b__0(FunctionArgument arg, IList`1 argList)
   at OfficeOpenXml.FormulaParsing.Excel.Functions.CollectionFlattener`1.FuncArgsToFlatEnumerable(IEnumerable`1 arguments, List`1 argList, Action`2 convertFunc)
   at OfficeOpenXml.FormulaParsing.Excel.Functions.CollectionFlattener`1.FuncArgsToFlatEnumerable(IEnumerable`1 arguments, Action`2 convertFunc)
   at OfficeOpenXml.FormulaParsing.Excel.Functions.DoubleEnumerableArgConverter.ConvertArgs(Boolean ignoreHidden, Boolean ignoreErrors, IEnumerable`1 arguments, ParsingContext context, Boolean ignoreNonNumeric)
   at OfficeOpenXml.FormulaParsing.Excel.Functions.ArgumentCollectionUtil.ArgsToDoubleEnumerable(Boolean ignoreHidden, Boolean ignoreErrors, IEnumerable`1 arguments, ParsingContext context, Boolean ignoreNonNumeric)
   at OfficeOpenXml.FormulaParsing.Excel.Functions.ExcelFunction.ArgsToDoubleEnumerable(Boolean ignoreHiddenCells, Boolean ignoreErrors, IEnumerable`1 arguments, ParsingContext context, Boolean ignoreNonNumeric)
   at OfficeOpenXml.FormulaParsing.Excel.Functions.Math.Min.Execute(IEnumerable`1 arguments, ParsingContext context)
   at OfficeOpenXml.FormulaParsing.ExpressionGraph.FunctionExpression.Compile()
```

It seems that OOXML does not play nicely when scientific notation is used within the IF function.

This can be reproduced with the following:
```
using OfficeOpenXml;

ExcelPackage.LicenseContext = LicenseContext.Commercial;
using var excelPack = new ExcelPackage(new FileInfo(@"C:\Users\jmiller\Desktop\Sample.xlsx"));
var worksheet = excelPack.Workbook.Worksheets.Add("Sample Worksheet");
worksheet.Cells["A1"].Value = "Active";
worksheet.Cells["B1"].Formula = "IF(A1 = \"Active\", 9E+30, 99)";
worksheet.Calculate();
Console.WriteLine(worksheet.Cells["B1"].Value.ToString());
excelPack.Save();
```

It is important to note, when opening the generated file, the Excel GUI shows it as 9E+30 as expected, but when attempting to read the value via code it results in a name error.

Thanks,

John

**Comment by swmal** [comment]
Thanks for reporting - we will have a look at this.

**Comment by swmal** [comment]
This is now fixed and will be included in the next version. It can be tested via our development nuget feed.

https://github.com/EPPlusSoftware/EPPlus/wiki/Using-our-develop-Nuget-feed
