### ISSUE TITLE
ArgumentOutOfRangeException when deleting rows with data validation

### ISSUE THREAD

**Issue by arnileibovits** [EPPlusSoftware/EPPlus#878]
Attached file contains data validation drop-downs. Deleting rows in this file causes an exception:
```
System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at OfficeOpenXml.Core.CellStore.RangeDictionary`1.DeleteRow(Int32 fromRow, Int32 noRows, Int32 fromCol, Int32 toCol)
   at OfficeOpenXml.DataValidation.ExcelDataValidationCollection.DeleteRangeInRangeDictionary(ExcelAddress address, Boolean shiftLeft)
   at OfficeOpenXml.DataValidation.ExcelDataValidationCollection.DeleteRangeDictionary(ExcelAddress address, Boolean shiftLeft)
   at OfficeOpenXml.Core.Worksheet.WorksheetRangeDeleteHelper.DeleteDataValidations(ExcelRangeBase range, eShiftTypeDelete shift, ExcelWorksheet ws, ExcelAddressBase effectedAddress)
   at OfficeOpenXml.Core.Worksheet.WorksheetRangeDeleteHelper.DeleteRow(ExcelWorksheet ws, Int32 rowFrom, Int32 rows)
   at OfficeOpenXml.ExcelWorksheet.DeleteRow(Int32 rowFrom, Int32 rows)
```

Code to reproduce:
```
var filePath = "Bug EPPlus delete rows 185161900.xlsx";
using var excelPackage = new ExcelPackage(filePath);

var sheet = excelPackage.Workbook.Worksheets[0];
sheet.DeleteRow(1, 100); // Throws ArgumentOutOfRangeException
```

Note that deleting rows one-by-one does not cause the exception.

EPPlus 6.2.1-6.2.3

[Bug EPPlus delete rows 185161900.xlsx](https://github.com/EPPlusSoftware/EPPlus/files/11486031/Bug.EPPlus.delete.rows.185161900.xlsx)

**Comment by arnileibovits** [comment]
Looks like this has been fixed in 6.2.4.
