### ISSUE TITLE
System.Drawing Dependency Causing Exception on Mac/Linux

### ISSUE THREAD

**Issue by yehia2amer** [EPPlusSoftware/EPPlus#93]
Is this Library .net core Compatible ?

When I try to run EPPlus App on Mac or Linux, I got that error !

```
[01:55:33 ERR] The type initializer for 'Gdip' threw an exception.
[01:55:33 ERR] System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibgdiplus, 1): image not found
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
[01:55:33 ERR] System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibgdiplus, 1): image not found
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipGetGenericFontFamilySansSerif(IntPtr& fontfamily)
   at System.Drawing.FontFamily.GetGdipGenericSansSerif()
   at System.Drawing.FontFamily.get_GenericSansSerif()
   at System.Drawing.Font.CreateFont(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte charSet, Boolean isVertical)
   at System.Drawing.Font..ctor(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth, Double MaximumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns(Double MinimumWidth)
   at OfficeOpenXml.ExcelRangeBase.AutoFitColumns()
   at CleanArchitecture.Domain.ExcelExporter.FormatTable(ExcelWorksheet wsDatadomainUsage, String rangeName, ExcelRangeBase range) in /Users/yehiaamer/Documents/Dell/Projects/TelemetryData/Domain/ExcelExporter.cs:line 197
   at CleanArchitecture.Domain.ExcelExporter.AddListToExcelTable[T](String tableName, ExcelWorksheet wsDatadomainUsage, List`1 ObjectList, String rangeName, Int32 startingTableRowNumber) in /Users/yehiaamer/Documents/Dell/Projects/TelemetryData/Domain/ExcelExporter.cs:line 86
   at CleanArchitecture.Domain.ExcelExporter.CreateExcel(List`1 genUsageInfo, List`1 licenseInfo, List`1 licenseFeaturesInfo, List`1 diskInfo) in /Users/yehiaamer/Documents/Dell/Projects/TelemetryData/Domain/ExcelExporter.cs:line 42
   at Domain.Runner.Run(String[] inputSerialsArray) in /Users/yehiaamer/Documents/Dell/Projects/TelemetryData/Domain/Runner.cs:line 48

```

**Comment by JanKallman** [comment]
Yes but System.Common.Drawing requires libgdiplus to work.
Try this:

Homebrew on MacOS:
brew install mono-libgdiplus

apt-get:
apt-get install libgdiplus

**Comment by JanKallman** [comment]
I updated the FAQ. Reopen if you don't get it to work.
